// <auto-generated />
namespace BettingApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class profile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(profile));
        
        string IMigrationMetadata.Id
        {
            get { return "201511260959538_profile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
